# Generated by Django 4.2.18 on 2026-02-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=2000)),
                ('bet', models.IntegerField(default=50)),
                ('round_active', models.BooleanField(default=False)),
                ('revealed_count', models.IntegerField(default=0)),
                ('current_multiplier', models.FloatField(default=1.0)),
                ('last_result_msg', models.CharField(default='', max_length=255)),
                ('bomb_positions', models.TextField(default='')),
                ('treasure_positions', models.TextField(default='')),
                ('grid', models.TextField(default='')),
            ],
        ),
    ]
