# Generated by Django 4.2.18 on 2026-02-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamestate',
            name='grid',
        ),
        migrations.RemoveField(
            model_name='gamestate',
            name='treasure_positions',
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='last_result_msg',
            field=models.CharField(default='', max_length=100),
        ),
    ]
